# Generated by Django 4.2.29 on 2026-03-06 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='租户名称')),
                ('tenant_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='租户ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
            },
        ),
    ]
