# Generated by Django 4.2.29 on 2026-03-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_userfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
